### ISSUE TITLE
Hypixel server seems to send hello packet too early

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [HypixelDev/ModAPI#25] opened 2024-05-18 21:01 UTC
~~Not too sure if this affects the official Mod API implementation~~ EDIT: Yes, it does affect the HypixelDev/ForgeModAPI implementation

On the Forge 1.8.9 client the value mc.netHandler depends on the player to be loaded in. 

Sometimes the hello packet is received before the S01JoinGame packet, causing the registration packet to fail to send

**Comment by ConnorLinfoot** [comment] 2024-05-18 21:31
We send the hello packet at the same time the standard registration occurs. If this is an order of operations issue in forge, we may need to store a local reference to the net handler from the server connect event and use that. But I'm not sure if this is the best solution to this issue.

**Comment by My-Name-Is-Jeff** [comment] 2024-05-18 22:46
> We send the hello packet at the same time the standard registration occurs. If this is an order of operations issue in forge, we may need to store a local reference to the net handler from the server connect event and use that. But I'm not sure if this is the best solution to this issue.

the issue is caused by how the JoinGame packet is handled on the Minecraft client thread (and has to wait) while the hello packet would be handled immediately on the Netty thread

**Comment by ConnorLinfoot** [comment] 2024-05-18 22:57
> > We send the hello packet at the same time the standard registration occurs. If this is an order of operations issue in forge, we may need to store a local reference to the net handler from the server connect event and use that. But I'm not sure if this is the best solution to this issue.
> 
> the issue is caused by how the JoinGame packet is handled on the Minecraft client thread (and has to wait) while the hello packet would be handled immediately on the Netty thread

In that case another option may be to schedule tasks onto the main thread and handling it from there. I did create https://github.com/HypixelDev/ForgeModAPI/pull/2 with holding reference, but if scheduling onto the main thread works then that is likely a better approach, so I'll look into that.

**Comment by ConnorLinfoot** [comment] 2024-06-16 18:59
This should be fixed with the 0.5.0 release. I've been unable to reproduce the issue but it was also less common for me in the first place, so do let me know if you still see some issues.

**Closed by ConnorLinfoot** 2024-06-16 18:59 UTC
